AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/application.rb'
    - 'config/environments/**/*'
    - 'Rakefile'
    - 'app/views/**/*.erb'  # ERBファイルはRuboCopでチェックしない

plugins:
  - rubocop-rails

# Line length
Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/**/*'     # 設定ファイルは長い行が許容される

# String literals - prefer single quotes
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Allow long blocks in specs and routes
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'db/seeds.rb'

# Allow longer methods in migrations and business logic
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'app/models/user.rb'            # OAuth処理
    - 'app/models/notification.rb'    # 通知作成メソッド群
    - 'app/models/month_end_closing.rb' # 月末締め処理
    - 'app/models/time_record.rb'     # 打刻順序バリデーション
    - 'app/models/application.rb'     # 申請タイプ別バリデーション
    - 'app/models/attendance.rb'      # 勤怠集計ビジネスロジック
    - 'app/models/monthly_summary.rb' # 月次集計ビジネスロジック
    - 'app/models/week.rb'            # 週管理ロジック
    - 'app/models/types/time_only.rb' # カスタム型定義
    - 'app/controllers/admin/users_controller.rb'  # 管理画面ロジック
    - 'app/controllers/shift_requests_controller.rb' # シフト登録ビジネスロジック
    - 'app/controllers/time_records_controller.rb'   # 打刻処理ロジック
    - 'app/controllers/attendances_controller.rb'    # 勤怠集計ロジック
    - 'app/services/**/*'             # サービスクラスの複雑なロジック

# Allow longer classes in controllers and complex models
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/models/user.rb'            # 権限管理とDevise統合で必然的に大きくなる
    - 'app/models/application.rb'     # 申請タイプ別バリデーション
    - 'app/models/approval.rb'        # ポリモーフィック承認システム
    - 'app/models/notification.rb'    # 通知システム
    - 'app/models/month_end_closing.rb' # 月末締め処理
    - 'app/models/attendance.rb'      # 勤怠集計ビジネスロジック
    - 'app/models/daily_schedule.rb'  # 日別スケジュールロジック
    - 'app/models/monthly_summary.rb' # 月次集計ビジネスロジック
    - 'app/services/**/*'             # サービスクラス

# Documentation is not required for all classes
Style/Documentation:
  Enabled: false

# Allow trailing commas in multi-line arrays and hashes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Prefer symbols array syntax
Style/SymbolArray:
  EnforcedStyle: brackets

# Rails specific configurations
Rails/UniqueValidationWithoutIndex:
  Enabled: false  # データベース設計段階で対応予定

Rails/I18nLocaleTexts:
  Enabled: false  # 現段階では国際化は不要

Rails/InverseOf:
  Exclude:
    - 'app/models/user.rb'  # 複雑な関連付けでinverse_ofが困難

# Complex business logic exceptions
Metrics/AbcSize:
  Exclude:
    - 'app/models/user.rb'            # OAuth処理
    - 'app/models/time_record.rb'     # 打刻順序バリデーション
    - 'app/models/application.rb'     # タイプ別バリデーション
    - 'app/models/attendance.rb'      # 勤怠集計ビジネスロジック
    - 'app/models/daily_schedule.rb'  # 日別スケジュールロジック
    - 'app/models/types/time_only.rb' # カスタム型定義
    - 'app/models/week.rb'            # 週管理ロジック
    - 'app/controllers/users/omniauth_callbacks_controller.rb'  # OAuth認証ロジック
    - 'app/controllers/shift_requests_controller.rb' # シフト登録ビジネスロジック
    - 'app/controllers/time_records_controller.rb'   # 打刻処理ロジック
    - 'app/controllers/attendances_controller.rb'    # 勤怠集計ロジック
    - 'app/services/**/*'             # サービスクラスの複雑なロジック
    - 'db/migrate/**/*'               # マイグレーションファイル

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/time_record.rb'     # 打刻順序バリデーション
    - 'app/models/application.rb'     # 申請タイプ別バリデーション
    - 'app/models/attendance.rb'      # 勤怠集計ビジネスロジック
    - 'app/models/types/time_only.rb' # カスタム型定義
    - 'app/controllers/time_records_controller.rb' # 打刻処理ロジック
    - 'app/services/**/*'             # サービスクラスの複雑なロジック

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/time_record.rb'     # 打刻順序バリデーション
    - 'app/models/application.rb'     # 申請タイプ別バリデーション
    - 'app/models/attendance.rb'      # 勤怠集計ビジネスロジック
    - 'app/models/types/time_only.rb' # カスタム型定義
    - 'app/controllers/time_records_controller.rb' # 打刻処理ロジック
    - 'app/services/**/*'             # サービスクラスの複雑なロジック

# Allow predicate method names for business logic
Naming/PredicateMethod:
  Exclude:
    - 'app/models/month_end_closing.rb'  # close_, lock_, reopen_メソッド群
    - 'app/models/weekly_shift.rb'       # validate_working_hoursはビジネスロジック

Naming/PredicatePrefix:
  Exclude:
    - 'app/models/user.rb'            # has_role?はDeviseパターン
    - 'app/models/daily_schedule.rb'  # has_*? はビジネスロジック
    - 'app/models/monthly_summary.rb' # has_violations?, is_over_monthly_limit?
    - 'app/models/weekly_shift.rb'    # has_violations?

# Rails patterns
Rails/WhereNotWithMultipleConditions:
  Enabled: false  # 複数条件のwhere.notは意図的

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/notification.rb'    # 一括既読更新

# Migration specific rules
Rails/BulkChangeTable:
  Enabled: false  # マイグレーションは段階的に作成されるため

Rails/ThreeStateBooleanColumn:
  Enabled: false  # 既存のデータベース設計に合わせる

